### DISCUSSION TITLE
能否添加windows_arm64的构建

### DISCUSSION THREAD

**Discussion by iwvw** [SPlayer-Dev/SPlayer#135] [Q&A] [answered]
如题

**Comment by imsyy** [comment, marked as answer]
可以自行修改  `electron-builder.yml`，我这就不改了，要不打包出来的文件太大了
```yml
win:
  # 构建类型
  target:
    - target: "nsis"
      arch:
        - "x64" # AMD64
    - target: "nsis"
      arch:
        - "ia32" # x86
    - target: "nsis"
      arch:
        - "arm64" # ARM64
```
